file_prefix = "GENERATED-"
mode = "BitmaskSlice"

output_type = "Cardinal"

[icon_size]
x = 32
y = 32

[output_icon_pos]
x = 0
y = 0

[output_icon_size]
x = 32
y = 32

[positions]
convex = 0
concave = 1
horizontal = 2
vertical = 3

[cut_pos]
x = 16
y = 16
