template = "bitmask/slice-32x32-diagonals"

[icon_size]
x = 64
y = 64

[output_icon_pos]
x = 0
y = 0

[output_icon_size]
x = 64
y = 64

[positions]
convex = 0
concave = 1
horizontal = 2
vertical = 3

[cut_pos]
x = 32
y = 32
